### ISSUE TITLE
M1.3: Provide availability monitoring and downtime alerting of matrix service

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/matrix-service#183] opened 2019-02-01 18:21 UTC
@morrisonnorman commented on [Tue Dec 11 2018](https://github.com/HumanCellAtlas/dcp/issues/239)

Relates to:
M1.3: Provide availability monitoring and downtime alerting of matrix service
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

---

@morrisonnorman commented on [Tue Dec 11 2018](https://github.com/HumanCellAtlas/dcp/issues/239#issuecomment-446205998)

@brianraymor  Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

---

@brianraymor commented on [Fri Dec 21 2018](https://github.com/HumanCellAtlas/dcp/issues/239#issuecomment-449519451)

This was addressed in the linked issue.

---

@brianraymor commented on [Fri Dec 21 2018](https://github.com/HumanCellAtlas/dcp/issues/239#issuecomment-449522304)

Reopening because there may be additional requirements in [System monitoring for General Availability](https://github.com/HumanCellAtlas/dcp-community/pull/53)

**Comment by brianraymor** [comment] 2019-02-13 00:31
This is a duplicate of #177. It was transitioned to _matrix-service_ as part of the cleanup of _dcp_.

**Closed by brianraymor** 2019-02-13 00:31 UTC
Labels: Epic
